spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
# Enter the password you use to log into pgAdmin below
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver