spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
# This must be the password you use to log into pgAdmin
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true